steps:
  - name: gcr.io/$PROJECT_ID/hugo
    args: [
      "-s","hugo",
      "-d","../public"
      ]

  # create a docker container that can run on cloud run
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "tools/preview_container/Dockerfile", "-t", "gcr.io/$PROJECT_ID/stanke-dev:pr-$_PR_NUMBER", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/stanke-dev:pr-$_PR_NUMBER"]

  # deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud@sha256:ffc20cf6058d8622d98ecfbfbfb4f2dc50bc2dfff245511a270e0098f885a7db
    entrypoint: gcloud
    args: 
      - alpha 
      - run 
      - deploy 
      - stanke-dev 
      - --revision-suffix=pr-$_PR_NUMBER
      - --image=gcr.io/stanke-dev/stanke-dev:pr-$_PR_NUMBER 
      - --platform=managed 
      - --region=us-central1 
      - --allow-unauthenticated 
      - --no-traffic
  
  # Set Cloud Run tag
  - name: gcr.io/cloud-builders/gcloud@sha256:ffc20cf6058d8622d98ecfbfbfb4f2dc50bc2dfff245511a270e0098f885a7db
    entrypoint: gcloud
    args: 
      - alpha 
      - run 
      - services
      - update-traffic 
      - stanke-dev 
      - --update-tags=pr-$_PR_NUMBER=stanke-dev-pr-$_PR_NUMBER
      - --platform=managed 
      - --region=us-central1

  - name: gcr.io/$PROJECT_ID/pr-commenter
    args: [
      "davidstanke/$REPO_NAME",
      "$_PR_NUMBER",
      "Preview this revision: https://pr-$_PR_NUMBER---stanke-dev-t63odkzjiq-uc.a.run.app"
    ]
    secretEnv: 
      - GITHUB_TOKEN

secrets:
  - kmsKeyName: projects/stanke-dev/locations/global/keyRings/stanke-dev/cryptoKeys/github-access-token
    secretEnv: 
      GITHUB_TOKEN: "\
      CiQApWZD3glqQqWrQokId3TuRrWfBMPTtu/B1ccsr+VKlAvFJGQSUQBLWP5TLHS\
      hG81/eGy20mkRBMYv/HBBlrAl+hCInE4UMXDerAFDBAUlV4gvt/32Idi1spAk/T8\
      PW8nsu8q946j7+9sP5mJo7ZBTauLmKYLLeg=="
